spring:
  profiles: 
    active: dev
  timerName: exampleTimer
  datasource:
    # driver-class-name: oracle.jdbc.driver.OracleDriver
    # url: jdbc:postgresql://172.16.20.235:5432
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.20.235:5432/postgres
    username: postgres
    password: 5gksghk
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
     ddl-auto: create-drop
    generate-ddl: true
---
# mybatis:
#   mapper-locations: classpath:mapper/**/*.xml
#   configuration:
#     lazyLoadingEnabled: true
#     aggressiveLazyLoading: false
#     mapUnderscoreToCamelCase: true

# spring:
#   profiles: local
#   task:
#     fixedDelay: 1000
#     name: localTask
#   datasource:
#     url: jdbc:oracle:thin:@localhost:1521:xe
#     username: vuetest
#     password: vuetest
# ---
# spring:
#   profiles: dev
#   task:
#     fixedDelay: 5000
#     name: devTask
#   datasource:
#     url: jdbc:oracle:thin:@localhost:1521:xe
#     username: vuetest
#     password: vuetest
# ---
# server:
#   port: 3030


# ---
spring:
  mvc:
    static-path-pattern: /static/**
